### ISSUE TITLE
Uploading a regular, static image can wipe out the service record for an item

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/NeatlineMaps#46]
There is a bug in the code that handles a new file upload that sometimes causes an existing WMS service record to be cleared out when a non-geotiff file is uploaded. It's not clear where the problem is, or what conditions trigger the problem (usually, things are fine).

Generally, to replicate:
- Create an item, add a WMS (either by directly entering data into the tab, or by uploading a .tiff)
- Then, upload a static image file on the item. Sometimes, this causes the WMS address and layers fields on the service record to get totally cleared out.

**Comment by waynegraham** [comment]
Cannot replicate; possible that this is a weird circumstance. Need to know what browser.

**Comment by jeremyboggs** [comment]
Also cannot replicate on Chrome, Safari, or Firefox. Pretty skeptical this is a browser-specific issue, unless we get more information.

**Comment by davidmcclure** [comment]
This is real. Basically, I think it happens in cases where you both (a) add web map service data and (b) add a static image in the _same editing session_ on the item (as in, whenever the new web service data and image are posted with the same form).

To replicate:
- Go to the add item form.
- Enter data in the "Web Map Service" tab and select a static image upload.
- Add the item

The image uploads, but the service data is not saved.

Alternately:
- Create an item without an image or map service.
- Edit the item.
- Enter data in the "Web Map Service" tab and select a static image upload.
- Save the item.

Again, the image gets uploaded, but the service data is not saved.

**Comment by jeremyboggs** [comment]
Yup, i did just duplicate this. Looks like the culprit is the [afterSaveItem method](https://github.com/scholarslab/NeatlineMaps/blob/develop/NeatlineMapsPlugin.php#L201) on the plugin. It's only saving those fields if the $_FILES array is empty, and not actually checking what the file is or contains. This should probably just check to see if Geoserver can do something with any of the uploaded files, like the afterInsertFile method on the plugin.
