### ISSUE TITLE
Plugin destroys server

### ISSUE THREAD

**Issue by ebonweaver** [scholarslab/NeatlineMaps#59]
Installing this plugin breaks Omeka entirely.  The entire system is now useless and only kicks out this code:

Fatal error: Uncaught Error: Call to a member function has() on array in /var/www/omeka/plugins/NeatlineMaps/NeatlineMapsPlugin.php:394 Stack trace: #0 /var/www/omeka/application/libraries/Omeka/Plugin/Broker.php(157): NeatlineMapsPlugin->defineAcl(Array) #1 /var/www/omeka/application/libraries/Omeka/Application/Resource/Acl.php(33): Omeka_Plugin_Broker->callHook('define_acl', Array) #2 /var/www/omeka/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(695): Omeka_Application_Resource_Acl->init() #3 /var/www/omeka/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(641): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('Acl') #4 /var/www/omeka/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('Acl') #5 /var/www/omeka/application/libraries/Omeka/Application/Resource/Helpers.php(120): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap('Acl') #6 /var/www/omeka/application/libraries/Omek in /var/www/omeka/plugins/NeatlineMaps/NeatlineMapsPlugin.php on line 394

**Comment by jeremyboggs** [comment]
This is a plugin for Omeka 1.5, and I'm guessing you're installing it on Omeka Classic (2.6) or something other than 1.5. That said, I did just try to install this on Omeka 2.6, and it didn't entirely break my system. But, since it did do something to yours, you should just delete NeatlineMaps in your plugins directory, and you should be able to access your Omeka site again.
